### ISSUE TITLE
Incorrect password crashes OnPremiseConnector

### ISSUE THREAD

**Issue by michelmoorlag** [thinktecture/relayserver#33]
### Actual behavior
When the password is incorrect the OnPremiseConnector crashes on a unhandeled: System.Exception: 'Could not authenticate with relay server: invalid_grant'
### Expected behavior
The connector should not crash but show a descriptive error explaining the problem in the eventviewer. 
### Steps to reproduce
Create a link in the relay server, setup the OnPremiseConnector with the password but type an extra random character in front of the password.
### Version
1.0.4, production zip
> master, develop, commit-hash, ...

**Comment by gingters** [comment]
Set to wont fix, as this behavior is as desired.

First of all, the OnPremiseConnectorService is just an example implementation of how this could work.
We would rather suggest to incorporate the Thinktecture.Relay.OnPremiseConnector directly into the target application which endpoints should be relayed with an OnPremiseInProcTargetConnector for real production use in order to avoid unnecessary http calls.
 
That said, the log output and the error message clearly states that it is not possible to authenticate with the relay server. Without a connection to the relay server, a connector would be completely useless. Also, this error is unrecoverable by itself. Unless someone changes the configuration and starts it again, the service would be useless, even if it would not crash.

Our stance on this is that it is better to fail fast and to fail hard in case of an unrecoverable error, especially within a pure demonstration project.
This way, the user is pointed directly at the underlying issue, instead of trying to figure out why the demo project which seems to be running fine is not connected.
