### ISSUE TITLE
Link shows connected but does not communicate

### ISSUE THREAD

**Issue by EbenZhang** [thinktecture/relayserver#332]
### Actual behavior

- On the management web, the link is green
- From client log, it's also connected
- Ping fails
- Client cannot receive any message from the server
- Issue remains after restarting the client (I tried more than 10 times, then issue disappeared after some time and not able to reproduce on the same PC)

### Expected behavior

The server should be able to ping and send message to the connected client.

### Steps to reproduce

Not sure, happens intermittently, more likely after a recreation/launch of the AWS EC2 instance, and only some clients are affected (but cannot find the pattern). 
We have two relay servers (AWS EC2 instance) behind AWS ALB, every time a new instance launched, the IP address is different, the Load Balance IP addresses are always the same.

When it happens:
- The client log shows connected like: `Connected to RelayServer xxxx with connection "2b344408-fa70-4ee4-8980-cea32bd2764c"`
- SignalR is active, the client keeps receiving `ws:OnMessage({})`, but cannot receive the heartbeat message from server. 
- The server log is like 
```
Sending Heartbeat. connection-id: 2b344408-fa70-4ee4-8980-cea32bd2764c
Waiting for response. request-id=e27023d5-cf9f-4d47-ab28-375343986e96, timeout="00:02:00"
Creating on-premise connector callback. request-id=e27023d5-cf9f-4d47-ab28-375343986e96
Forwarding client request to connection. connection-id=..., request-id=..., http-method=HEARTBEAT, url=, origin-id="c8c89770-f89f-4af8-bd0b-268b1f179b72", body-length=0
No response received within specified timeout. callback-timeout="00:00:30", request-id=e27023d5-cf9f-4d47-ab28-375343986e96
```
- On management website, the connection id 2b344408-fa70-4ee4-8980-cea32bd2764c doesn't appear in the link details. All connections are inactive.
![image](https://user-images.githubusercontent.com/596334/110937581-8884a380-836d-11eb-840b-41089eb91b11.png)

BTW above image is not the full list, and I don't know why connection of year 2019 is still in the list (maybe we don't purge the history?)

### Version

2.3.0 relayserver + this memcached plugin: https://github.com/jasminsehic/relayserver-custominterceptors
2.3.0 client as well as 2.2.0 client

**Comment by gingters** [comment]
Hi,

this is a issue that we have seen before. This situation can happen, when the relay servers are behind certain load balancers. We noticed that especially with Netscaler so far.

The main issue is that a SignalR connection gets established, but for whatever reason the messages that the server sends to the connector don't get through. Server says it has sent the message, but the connector never receives it. This is what I call an "immediately broken connection". I suspect the loadbalancer drops the websocket frames, but we never had the opportunity to wireshark both ends of an LB to prove it.

For the connection (2b344...) not in the list: When we deactivate a connection (i.e. because it does not respond to heartbeats) we delete the connection from the database. This is why you don't find your connection there.

For the (huge) list of inactive connections:
We clean up all old connections to a server (identified by the origin id), when a server restarts (i.e. after a crash). The origin id is persisted in a file in local app data. So when you shutdown a server for good and i.e. deploy a new version of RelayServer to a new (virtual) machine that does not has the persisted appdata file, the new instance will create a new origin id, and all connections to the old Guid will remain in the database forever (this is done differently in Relay v3).

So to solve that you can check the current origin id's of your servers and simply delete all connections from the table that have a different origin id (these are old ones). You should do that whenever you deploy to a new VM or lose a previous used origin id. In theory you could also delete all connections and the current active ones should be entered again automatically.

The green connect dot on the management web only checks if there are any connection entries in the database for that link (no matter how old). Inactive only means the last activity is older than a specific threshold. Since deactivated connections are removed here, these should not lead to the erroneous indication of an active connection.

Sadly, this will only fix the (wrong) indication of an active connection, but does not really fix the underlying problem, the broken connections.

We sadly don't see a real fix for that.

We can't fix that on the server side: The SignalR server api does not offer any means to disconnect a client from the server. Not even internal APIs. Even if we know that frames don't make it all the way down, we cant disconnect the client, and we also can't notify the client with a message to disconnect itself, as it won't reach the connector when the connection is broken that way.

For the connector side, we need to be back- and forward compatible with RelayServer 1.x and 2.x servers and connectors. Older connectors can connect to newer servers, and new connectors can connect to older servers.

A connector that connects to a server does not know what version the server has. It could be an old server that does not yet support heartbeating. So the connector has to wait for the first heartbeat to arrive from the server until it starts its broken connection detection on the connector side. Only if it got an initial heartbeat, it starts listening for further ones and if they stop, then the connector closes the SignalR connection and re-establishes a new one. Because of the immediately broken connection, that very first heartbeat never reaches the client. So the client assumes it is connected to an older server that does not yet support heartbeats, and stays connected.

We can't change that behavior (at least by default), because then a newer connector that requires a heartbeat won't be compatible with older servers that don't support heartbeats anymore.

We could, however, think of a way that allows to enable such a behavior (require heartbeats to be received) by configuration (and opt out of backwards-compat that way).

That said, we are currently more focused on the rewrite of RelayServer (v3) on .NET Core and the new SignalR protocol (where we did not see these kind of issues so far), and that will be way more resilient to connection issues like this. We have a working pre-alpha of v3 in the repo, but it will take some time until this is ready.

**Comment by jasminsehic** [comment]
@EbenZhang I've tried solving this by forcing disconnections from client side before, this would be in the process hosting the RelayServer On-Premise Connector Assembly. Perhaps there is more that can be done from on-premise client side such as disconnecting if no heartbeat is detected.

**Comment by EbenZhang** [comment]
@jasminsehic  I think this one is different, in this case the issue remains even after the client application restarted (for quite a long time, but I can't remember how long, gutter feeling is at least 1 hour).

**Comment by jasminsehic** [comment]
Right OK. You may have to look at tweaking connection timeouts perhaps
between ELB/ALB to EC2 or try to detect stale connections there.

**Comment by jasminsehic** [comment]
@EbenZhang also forgot to mention it may be worth looking at switching between Classic ELB and ALB, and switching to HTTP 1, away from HTTP/2 which has streaming as that could be causing the connection between LB to EC2 to stay open for longer. Hopefully you see some difference in how connection between LB and EC2 there behaves and one of those doesn't have the issue or less of an issue.

**Comment by thomashilzendegen** [comment]
Closing due to the release of RelayServer 3.0.0, because no further development is done in the previous version anymore.
